name: Deploy Astro to GitHub Pages

on:
  # デフォルトブランチへのプッシュで実行
  push:
    branches: ["main"]

  # Actionsタブから手動実行も可能
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限設定
permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Poppler and other required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils ghostscript pdftk

#      - name: Convert PDFs to images
#        run: npm run convert

      - name: compress pdf
        run: |
          for pdf in public/pdfs/*.pdf; do
            file_size=$(stat -c%s "$pdf")
            if [ "$file_size" -gt $((24 * 1024 * 1024)) ]; then
              echo "Compressing $pdf"
              gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${pdf%.pdf}_compressed.pdf" "$pdf"
              # 圧縮したファイルに置き換え
              mv "${pdf%.pdf}_compressed.pdf" "$pdf"
            fi
           done

      - name: Build Astro site
        run: npm run build
        env:
          VITE_GITHUB_ACTIONS: true
          NODE_OPTIONS: --max-old-space-size=4096
          VITE_GITHUB_REPOSITORY_OWNER: ${{ github.event.repository.owner.login }}
          VITE_GITHUB_REPOSITORY: ${{ github.event.repository.name }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish --project-name=slide-tubone24 ./dist
